In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv("customers (1).csv")
geolocation = pd.read_csv("geolocation.csv")
order_items = pd.read_csv("order_items.csv")
order_reviews = pd.read_csv("order_reviews.csv", encoding="latin1")
orders = pd.read_csv("orders (1).csv")
payments = pd.read_csv("payments.csv")
products = pd.read_csv("products (1).csv")
sellers = pd.read_csv("sellers.csv")

In [3]:
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "order_reviews": order_reviews,
    "orders": orders,
    "payments": payments,
    "products": products,
    "sellers": sellers
}

In [4]:
for name,dset in datasets.items():
    print()
    print(name.upper())
    print(dset.info())
    print(dset.head())
    print(dset.describe(include="all"))

CUSTOMERS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP
                             customer_id                customer_unique_id  \
count                              99441                             99441
unique                             99441                             96096
top     06b8999e2fba1a1fbc88172c00ba8bc7  8d50f5eadf50201ccdcedfb9e2ac8455
freq                                   1                                17
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        customer_zip_code_prefix customer_city customer_state
count               99441.000000         99441          99441
unique                       NaN          4119             27
top                          NaN     sao paulo             SP
freq                         NaN         15540          41746
mean                35137.474583           NaN            NaN
std                 29797.938996           NaN            NaN
min                  1003.000000           NaN            NaN
25%                 11347.000000           NaN            NaN
50%                 24416.000000           NaN            NaN
75%                 58900.000000           NaN            NaN
max                 99990.000000           NaN            NaN

GEOLOCATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP
        geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
count                  1.000163e+06     1.000163e+06     1.000163e+06
unique                          NaN              NaN              NaN
top                             NaN              NaN              NaN
freq                            NaN              NaN              NaN
mean                   3.657417e+04    -2.117615e+01    -4.639054e+01
std                    3.054934e+04     5.715866e+00     4.269748e+00
min                    1.001000e+03    -3.660537e+01    -1.014668e+02
25%                    1.107500e+04    -2.360355e+01    -4.857317e+01
50%                    2.653000e+04    -2.291938e+01    -4.663788e+01
75%                    6.350400e+04    -1.997962e+01    -4.376771e+01
max                    9.999000e+04     4.506593e+01     1.211054e+02

       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268
mean                NaN               NaN
std                 NaN               NaN
min                 NaN               NaN
25%                 NaN               NaN
50%                 NaN               NaN
75%                 NaN               NaN
max                 NaN               NaN

ORDER_ITEMS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14
                                order_id  order_item_id  \
count                             112650  112650.000000
unique                             98666            NaN
top     8272b63d03f5f79c56e9e4120aec44ef            NaN
freq                                  21            NaN
mean                                 NaN       1.197834
std                                  NaN       0.705124
min                                  NaN       1.000000
25%                                  NaN       1.000000
50%                                  NaN       1.000000
75%                                  NaN       1.000000
max                                  NaN      21.000000

                              product_id                         seller_id  \
count                             112650                            112650
unique                             32951                              3095
top     aca2eb7d00ea1a7b8ebd4e68314663af  6560211a19b47992c3666cc44a7e94c0
freq                                 527                              2033
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        shipping_limit_date          price  freight_value
count                112650  112650.000000  112650.000000
unique                93318            NaN            NaN
top     2017-07-21 18:25:23            NaN            NaN
freq                     21            NaN            NaN
mean                    NaN     120.653739      19.990320
std                     NaN     183.633928      15.806405
min                     NaN       0.850000       0.000000
25%                     NaN      39.900000      13.080000
50%                     NaN      74.990000      16.260000
75%                     NaN     134.900000      21.150000
max                     NaN    6735.000000     409.680000

ORDER_REVIEWS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11547 non-null  object
 4   review_creation_date     99224 non-null  object
 5   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.5+ MB
None
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title review_creation_date  \
0             4                  NaN        18/01/18 0:00
1             5                  NaN        10/03/18 0:00
2             5                  NaN        17/02/18 0:00
3             5                  NaN        21/04/17 0:00
4             5                  NaN        01/03/18 0:00

  review_answer_timestamp
0          18/01/18 21:46
1           11/03/18 3:05
2          18/02/18 14:36
3          21/04/17 22:02
4          02/03/18 10:26
                               review_id                          order_id  \
count                              99224                             99224
unique                             98410                             98673
top     7b606b0d57b078384f0b58eac1d41d78  c88b1d1b157a9999ce368f218a407141
freq                                   3                                 3
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        review_score review_comment_title review_creation_date  \
count   99224.000000                11547                99224
unique           NaN                 3364                  636
top              NaN          I recommend        19/12/17 0:00
freq             NaN                 1063                  463
mean        4.086421                  NaN                  NaN
std         1.347579                  NaN                  NaN
min         1.000000                  NaN                  NaN
25%         4.000000                  NaN                  NaN
50%         5.000000                  NaN                  NaN
75%         5.000000                  NaN                  NaN
max         5.000000                  NaN                  NaN

       review_answer_timestamp
count                    99224
unique                   88867
top             12/08/17 14:35
freq                         6
mean                       NaN
std                        NaN
min                        NaN
25%                        NaN
50%                        NaN
75%                        NaN
max                        NaN

ORDERS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-04-11 10:48:14  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-08 23:38:46
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522

PAYMENTS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45
                                order_id  payment_sequential payment_type  \
count                             103886       103886.000000       103886
unique                             99440                 NaN            5
top     fa65dad1b0e818e3ccc5cb0e39231352                 NaN  credit_card
freq                                  29                 NaN        76795
mean                                 NaN            1.092679          NaN
std                                  NaN            0.706584          NaN
min                                  NaN            1.000000          NaN
25%                                  NaN            1.000000          NaN
50%                                  NaN            1.000000          NaN
75%                                  NaN            1.000000          NaN
max                                  NaN           29.000000          NaN

        payment_installments  payment_value
count          103886.000000  103886.000000
unique                   NaN            NaN
top                      NaN            NaN
freq                     NaN            NaN
mean                2.853349     154.100380
std                 2.687051     217.494064
min                 0.000000       0.000000
25%                 1.000000      56.790000
50%                 1.000000     100.000000
75%                 4.000000     171.837500
max                24.000000   13664.080000

PRODUCTS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product category            32341 non-null  object
 2   product_name_length         32341 non-null  float64
 3   product_description_length  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None
                         product_id product category  product_name_length  \
0  1e9e8ef04dbcff4541ed26657ea517e5        perfumery                 40.0

In [5]:
products.isnull().sum()

product_id                      0
product category              610
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [6]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]
for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [9]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [10]:
orders.duplicated().sum()

np.int64(0)

In [11]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [12]:
orders[date_columns].isnull().sum()

order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [13]:
orders["delivery_time_days"] = (
    orders["order_delivered_customer_date"] -
    orders["order_purchase_timestamp"]
).dt.days
#if we dont write dt.days, exact delivery is calculated (with timestamps too, instead of just days), like this "8 days 10:28:40"

In [14]:
orders["delivery_time_days"]

0         8.0
1        13.0
2         9.0
3        13.0
4         2.0
         ...
99436     8.0
99437    22.0
99438    24.0
99439    17.0
99440     7.0
Name: delivery_time_days, Length: 99441, dtype: float64

In [15]:
orders["delivery_time_days"] = orders["delivery_time_days"].astype("Int64")

In [16]:
orders["delivery_time_days"]

0         8
1        13
2         9
3        13
4         2
         ..
99436     8
99437    22
99438    24
99439    17
99440     7
Name: delivery_time_days, Length: 99441, dtype: Int64

In [17]:
orders["estimated_delivery_days"] = (
    orders["order_estimated_delivery_date"] -
    orders["order_purchase_timestamp"]
).dt.days.astype("Int64")

In [18]:
orders["estimated_delivery_days"]

0        15
1        19
2        26
3        26
4        12
         ..
99436    18
99437    23
99438    30
99439    37
99440    25
Name: estimated_delivery_days, Length: 99441, dtype: Int64

In [19]:
orders["delivery_delay_days"] = (
    orders["order_delivered_customer_date"] -
    orders["order_estimated_delivery_date"]
).dt.days.astype("Int64")

In [20]:
orders["delivery_delay_days"]

0         -8
1         -6
2        -18
3        -13
4        -10
        ...
99436    -11
99437     -2
99438     -6
99439    -21
99440    -18
Name: delivery_delay_days, Length: 99441, dtype: Int64

In [21]:
def time_of_day(hour):
    if 0 <= hour < 7:
        return "Dawn"
    elif 7 <= hour < 13:
        return "Morning"
    elif 13 <= hour < 19:
        return "Afternoon"
    else:
        return "Night"

orders["time_of_day"] = orders["order_purchase_timestamp"].dt.hour.apply(time_of_day)

In [22]:
orders["time_of_day"]

0          Morning
1            Night
2          Morning
3            Night
4            Night
           ...
99436      Morning
99437      Morning
99438    Afternoon
99439        Night
99440        Night
Name: time_of_day, Length: 99441, dtype: object

In [23]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_time_days             96476 non-null  Int64
 9   estimated_delivery_days        99441 non-null  Int64
 10  delivery_delay_days            96476 non-null  Int64
 11  time_of_day                    99441 non-null  object
dtypes: Int64(3), datetime64[ns](5), object(4)
memory usage: 9.4+ MB

In [24]:
products.isnull().sum()

product_id                      0
product category              610
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [25]:
products.duplicated().sum()

np.int64(0)

In [26]:
products.rename(columns={"product category": "product_category"}, inplace=True)

In [27]:
products["product_category"] = products["product_category"].fillna("Unknown")

In [28]:
num_cols = [
    "product_name_length",
    "product_description_length",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

for col in num_cols:
    products[col] = products[col].fillna(products[col].median())

In [29]:
products[num_cols] = products[num_cols].astype(int)

In [30]:
(products["product_weight_g"] == 0).sum()

np.int64(4)

In [31]:
products[products["product_weight_g"] == 0]

,product_id,product_category,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,bed table bath,51,529,1,0,30,25,30
13683,8038040ee2a71048d4bdbbdc985b69ab,bed table bath,48,528,1,0,30,25,30
14997,36ba42dd187055e1fbe943b2d11430ca,bed table bath,53,528,1,0,30,25,30
32079,e673e90efa65a5409ff4196c038bb5af,bed table bath,53,528,1,0,30,25,30

In [32]:
#all are of same category, so we cant rlly use groupby unless there are more than 4 items in same category, so we check them

products["product_category"].value_counts()

product_category
bed table bath                 3029
sport leisure                  2867
Furniture Decoration           2657
HEALTH BEAUTY                  2444
housewares                     2335
                               ...
Fashion Children's Clothing       5
House Comfort 2                   5
PC Gamer                          3
insurance and services            2
cds music dvds                    1
Name: count, Length: 74, dtype: int64

In [33]:
import numpy as np

In [34]:
# Replace 0 with nan
products["product_weight_g"] = products["product_weight_g"].replace(0, np.nan)

# Fill with the median weight of each category
products["product_weight_g"] = products["product_weight_g"].fillna(
    products.groupby("product_category")["product_weight_g"].transform("median")
)

# Convert to integer
products["product_weight_g"] = products["product_weight_g"].astype(int)

In [35]:
(products["product_weight_g"] == 0).sum()

np.int64(0)

In [36]:
products["product_volume_cm3"] = (
    products["product_length_cm"] *
    products["product_width_cm"] *
    products["product_height_cm"]
)

In [37]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category            32951 non-null  object
 2   product_name_length         32951 non-null  int64
 3   product_description_length  32951 non-null  int64
 4   product_photos_qty          32951 non-null  int64
 5   product_weight_g            32951 non-null  int64
 6   product_length_cm           32951 non-null  int64
 7   product_height_cm           32951 non-null  int64
 8   product_width_cm            32951 non-null  int64
 9   product_volume_cm3          32951 non-null  int64
dtypes: int64(8), object(2)
memory usage: 2.5+ MB

In [38]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [39]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [40]:
customers.duplicated().sum()

np.int64(0)

In [41]:
customers["customer_city"] = customers["customer_city"].str.title()

In [42]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [43]:
geolocation[geolocation.duplicated()]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [44]:
geolocation.drop_duplicates(inplace=True)

In [45]:
# geolocation.reset_index(drop=True, inplace=True) - not necessary, but will make the index numbers ordered. we removed index 15,44 etc, but pandas doent automatically adjust indices, so we use this to adjust indices

In [46]:
geolocation["geolocation_city"] = geolocation["geolocation_city"].str.title()

In [47]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [48]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [49]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])

In [50]:
order_items.duplicated().sum()

np.int64(0)

In [51]:
(order_items["price"] < 0).sum()

np.int64(0)

In [52]:
(order_items["freight_value"] < 0).sum()

np.int64(0)

In [53]:
order_items["total_item_cost"] = (order_items["price"] + order_items["freight_value"])

In [54]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11547 non-null  object
 4   review_creation_date     99224 non-null  object
 5   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.5+ MB

In [55]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,18/01/18 0:00,18/01/18 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,10/03/18 0:00,11/03/18 3:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,17/02/18 0:00,18/02/18 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,21/04/17 0:00,21/04/17 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,01/03/18 0:00,02/03/18 10:26

In [56]:
order_reviews["review_creation_date"] = pd.to_datetime(order_reviews["review_creation_date"],format="%d/%m/%y %H:%M")
order_reviews["review_answer_timestamp"] = pd.to_datetime(order_reviews["review_answer_timestamp"],format="%d/%m/%y %H:%M")

In [57]:
order_reviews.duplicated().sum()

np.int64(0)

In [58]:
order_reviews["review_score"].value_counts()

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

In [59]:
order_reviews["review_comment_title"] = order_reviews["review_comment_title"].fillna("No Title")

In [60]:
order_reviews["review_response_days"] = (order_reviews["review_answer_timestamp"] - order_reviews["review_creation_date"]).dt.days

In [61]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [62]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [63]:
payments.duplicated().sum()

np.int64(0)

In [64]:
(payments["payment_value"] <= 0).sum()

np.int64(9)

In [65]:
# Remove invalid payment values
payments = payments[payments["payment_value"] > 0].copy()

In [66]:
(payments["payment_installments"] < 0).sum()

np.int64(0)

In [67]:
(payments["payment_installments"] == 0).sum()

np.int64(2)

In [68]:
payments[payments["payment_installments"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [69]:
payments.loc[
    payments["payment_installments"] == 0,
    "payment_installments"
] = 1

# Corrected two anomalous credit card payments with 0 installments to 1 installment.

In [70]:
payments["payment_category"] = payments["payment_installments"].apply(
    lambda x: "Installment" if x > 1 else "Single Payment"
)

In [71]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [72]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [73]:
sellers.duplicated().sum()

np.int64(0)

In [74]:
sellers["seller_city"] = sellers["seller_city"].str.title()

In [75]:
for name,dset in datasets.items():
    print(name.upper())
    print(dset.info())
    print()
    print(dset.head())
    print()

CUSTOMERS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 Franca             SP
1                      9790  Sao Bernardo Do Campo             SP
2                      1151              Sao Paulo             SP
3                      8775        Mogi Das Cruzes             SP
4                     13056               Campinas             SP

GEOLOCATION
<class 'pandas.core.frame.DataFrame'>
Index: 738332 entries, 0 to 1000161
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  int64
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  object
 4   geolocation_state            738332 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 33.8+ MB
None

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        Sao Paulo                SP
1        Sao Paulo                SP
2        Sao Paulo                SP
3        Sao Paulo                SP
4        Sao Paulo                SP

ORDER_ITEMS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   total_item_cost      112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 6.9+ MB
None

                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

  shipping_limit_date   price  freight_value  total_item_cost
0 2017-09-19 09:45:35   58.90          13.29            72.19
1 2017-05-03 11:05:13  239.90          19.93           259.83
2 2018-01-18 14:48:30  199.00          17.87           216.87
3 2018-08-15 10:10:18   12.99          12.79            25.78
4 2017-02-13 13:57:51  199.90          18.14           218.04

ORDER_REVIEWS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  object
 4   review_creation_date     99224 non-null  datetime64[ns]
 5   review_answer_timestamp  99224 non-null  datetime64[ns]
 6   review_response_days     99224 non-null  int64
dtypes: datetime64[ns](2), int64(2), object(3)
memory usage: 5.3+ MB
None

                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title review_creation_date  \
0             4             No Title           2018-01-18
1             5             No Title           2018-03-10
2             5             No Title           2018-02-17
3             5             No Title           2017-04-21
4             5             No Title           2018-03-01

  review_answer_timestamp  review_response_days
0     2018-01-18 21:46:00                     0
1     2018-03-11 03:05:00                     1
2     2018-02-18 14:36:00                     1
3     2017-04-21 22:02:00                     0
4     2018-03-02 10:26:00                     1

ORDERS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_time_days             96476 non-null  Int64
 9   estimated_delivery_days        99441 non-null  Int64
 10  delivery_delay_days            96476 non-null  Int64
 11  time_of_day                    99441 non-null  object
dtypes: Int64(3), datetime64[ns](5), object(4)
memory usage: 9.4+ MB
None

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39 2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date  delivery_time_days  estimated_delivery_days  \
0                    2017-10-18                   8                       15
1                    2018-08-13                  13                       19
2                    2018-09-04                   9                       26
3                    2017-12-15                  13                       26
4                    2018-02-26                   2                       12

   delivery_delay_days time_of_day
0                   -8     Morning
1                   -6       Night
2                  -18     Morning
3                  -13       Night
4                  -10       Night

PAYMENTS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

PRODUCTS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category            32951 non-null  object
 2   product_name_length         32951 non-null  int64
 3   product_description_length  32951 non-null  int64
 4   product_photos_qty          32951 non-null  int64
 5   product_weight_g            32951 non-null  int64
 6   product_length_cm           32951 non-null  int64
 7   product_height_cm           32951 non-null  int64
 8   product_width_cm            32951 non-null  int64
 9   product_volume_cm3          32951 non-null  int64
dtypes: int64(8), object(2)
memory usage: 2.5+ MB
None

                         product_id product_category  product_name_length  \
0  1e9e8ef04dbcff4541ed26657ea517e5        perfumery                   40
1  3aa071139cb16b67ca9e5dea641aaa2f              Art                   44
2  96bd76ec8810374ed1b65e291975717f    sport leisure                   46
3  cef67bcfe19066a932b7673e239eb23d           babies                   27
4  9dc1a7de274444849c219cff195d0b71       housewares                   37

   product_description_length  product_photos_qty  product_weight_g  \
0                         287                   1               225
1                         276                   1              1000
2                         250                   1               154
3                         261                   1               371
4                         402                   4               625

   product_length_cm  product_height_cm  product_width_cm  product_volume_cm3
0                 16                 10                14                2240
1                 30                 18                20               10800
2                 18                  9                15                2430
3                 26                  4                26                2704
4                 20                 17                13                4420

SELLERS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None

                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           Campinas           SP
1         Mogi Guacu           SP
2     Rio De Janeiro           RJ
3          Sao Paulo           SP
4  Braganca Paulista           SP

In [76]:
customers.to_csv("customers_cleaned.csv", index=False)
geolocation.to_csv("geolocation_cleaned.csv", index=False)
order_items.to_csv("order_items_cleaned.csv", index=False)
order_reviews.to_csv("order_reviews_cleaned.csv", index=False)
orders.to_csv("orders_cleaned.csv", index=False)
payments.to_csv("payments_cleaned.csv", index=False)
products.to_csv("products_cleaned.csv", index=False)
sellers.to_csv("sellers_cleaned.csv", index=False)

In [ ]:
!pip install pymysql sqlalchemy

In [ ]:
from sqlalchemy import create_engine

# MySQL connection
username = "your_username"
password = "your_password"
host = "localhost"
port = "3306"
database = "your_database"

engine = create_engine(
    "mysql+pymysql://username:password@host:port/database"
)

In [79]:
customers.to_sql("customers", engine, if_exists="replace", index=False)

99441

In [ ]:
pd.read_sql("SHOW TABLES;", engine)

In [81]:
geolocation.to_sql("geolocation", engine, if_exists="replace", index=False)
order_items.to_sql("order_items", engine, if_exists="replace", index=False)
order_reviews.to_sql("order_reviews", engine, if_exists="replace", index=False)
orders.to_sql("orders", engine, if_exists="replace", index=False)
payments.to_sql("payments", engine, if_exists="replace", index=False)
products.to_sql("products", engine, if_exists="replace", index=False)
sellers.to_sql("sellers", engine, if_exists="replace", index=False)

3095

In [82]:
pd.read_sql("SHOW TABLES;", engine)

  Tables_in_marketing_analysis
0                    customers
1                  geolocation
2                  order_items
3                order_reviews
4                       orders
5                     payments
6                     products
7                      sellers